global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metaverse-node'
    static_configs:
      - targets: ['metaverse-node:8545']

  - job_name: 'quantum-sim'
    static_configs:
      - targets: ['quantum-sim:5000']

  - job_name: 'private-chain'
    static_configs:
      - targets: ['private-chain:8546']

  - job_name: 'xor-storage'
    static_configs:
      - targets: ['xor-storage:8547']

  - job_name: 'foa-contracts'
    static_configs:
      - targets: ['foa-contracts:8548']
